apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/dtsulik/homelab-gitops.git
          revision: HEAD
          directories:
          - path: apps/*
      - list:
          elements:
          - cluster: homelab-vm
            url: https://kubernetes.default.svc
            values:
              project: default
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: dtsulik/gif-doggo-apigw:master,dtsulik/gif-doggo-intake:master,dtsulik/gif-doggo-output:master,dtsulik/gif-doggo-process:master,dtsulik/gif-doggo-request:master,dtsulik/gif-doggo-status:master
        argocd-image-updater.argoproj.io/update-strategy: digest
        argocd-image-updater.argoproj.io/allow-tags: regexp:master
      name: '{{path.basename}}-{{cluster}}'
    spec:
      syncPolicy:
        automated:
          prune: true
      project: '{{values.project}}'
      source:
        repoURL: https://github.com/dtsulik/homelab-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: '{{path.basename}}'