apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/dtsulik/homelab-gitops.git
          revision: HEAD
          directories:
          - path: apps/*
      - list:
          elements:
          - cluster: homelab-vm
            url: https://kubernetes.default.svc
            values:
              project: default
  template:
    metadata:
      name: '{{path.basename}}-{{cluster}}'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: https://github.com/dtsulik/homelab-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: '{{path.basename}}'