apiVersion: v2
name: gif-doggo-status
description: Microservice for getting doggo request status
type: application
version: 0.0.4
appVersion: "0.0.4"

dependencies:
  - name: app-template
    version: 0.0.4
    repository: "file://../../library/app-template/"