apiVersion: v2
name: gif-doggo-bff
description: Backend for frontend for doggos
type: application
version: 0.0.4
appVersion: "0.0.4"

dependencies:
  - name: app-template
    version: 0.0.4
    repository: "file://../../library/app-template/"