apiVersion: v2
appVersion: 0.0.4
description: Microservice stack for generating doggos
name: gif-doggo
version: 0.0.38
dependencies:
    - name: app-template
      version: 0.0.18
      repository: file://../library/app-template/
      condition: ""
    - name: gif-doggo-apigw
      version: 0.0.14
      repository: file://../micro-services/apigw/
      condition: gif-doggo-apigw.enabled
    - name: gif-doggo-intake
      version: 0.0.14
      repository: file://../micro-services/intake/
      condition: gif-doggo-intake.enabled
    - name: gif-doggo-output
      version: 0.0.14
      repository: file://../micro-services/output/
      condition: gif-doggo-output.enabled
    - name: gif-doggo-process
      version: 0.0.14
      repository: file://../micro-services/process/
      condition: gif-doggo-process.enabled
    - name: gif-doggo-request
      version: 0.0.14
      repository: file://../micro-services/request/
      condition: gif-doggo-request.enabled
    - name: gif-doggo-status
      version: 0.0.14
      repository: file://../micro-services/status/
      condition: gif-doggo-status.enabled
    - name: redis
      version: 17.3.24
      repository: https://charts.bitnami.com/bitnami
      condition: redis.enabled
