apiVersion: v2
name: gif-doggo
description: Microservice stack for generating doggos
type: application
version: 0.0.4
appVersion: "0.0.4"

dependencies:
  - name: app-template
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"
  - name: redis
    condition: redis.enabled
    version: 17.3.14
    repository: "https://charts.bitnami.com/bitnami"
  - name: gif-doggo-apigw
    condition: gif-doggo-apigw.enabled
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"
  - name: gif-doggo-intake
    condition: gif-doggo-intake.enabled
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"
  - name: gif-doggo-output
    condition: gif-doggo-output.enabled
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"
  - name: gif-doggo-process
    condition: gif-doggo-process.enabled
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"
  - name: gif-doggo-request
    condition: gif-doggo-request.enabled
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"
  - name: gif-doggo-status
    condition: gif-doggo-status.enabled
    version: 0.0.4
    repository: "https://dtsulik.github.io/gif-doggo/"