apiVersion: v2
name: gif-doggo-bff
description: BFF doggo
type: application
version: 0.0.4
appVersion: "0.0.4"

dependencies:
  - name: app-template
    version: 0.0.4
    repository: "file://../../templates/app-template/"